### ISSUE TITLE
Unable to destroy `foreman_host`

### ISSUE THREAD

**Issue by jzandbergen** [HanseMerkur/terraform-provider-foreman#43]
Hi All,

I'm trying out this terraform provider and i'm having an issue where i'm unable to destroy a `foreman_host` resource.

## My `main.tf`
```
terraform{
  required_providers {
    foreman = {
      source = "HanseMerkur/foreman"
      version = "0.4.1"
    }
  }
}

provider "foreman" {
  server_hostname = "foreman.virtualt00bz.lan"
  server_protocol = "https"
  client_tls_insecure = true
  client_username = "terraform"
  client_password = REDACTED but is was super secure, believe me. It was _not_ "password" ;)
  location_id = 2
  organization_id = 1
}


resource "foreman_host" "test123" {
  name = "test123"
  hostgroup_id = 3
  domain_id = 1
  compute_resource_id = 1
  compute_profile_id = 5
  compute_attributes = jsonencode({"image_id"="/var/lib/libvirt/images/alpine-3.13-cloud.qcow2"})
  medium_id = 14
  method = "image"
  interfaces_attributes {
    type = "interface"
    managed = true
    primary = true
  }
  lifecycle {
    ignore_changes = [
      name,
      compute_attributes,
      interfaces_attributes,
      owner_id,
      image_id,
      owner_type,
    ]
  }
}
```
I've included the `ignore_changes` part, because if I don't, terraform wants to update my resource every time I run `terraform apply`.

## terraform apply
So now I can apply it, no problem here:
```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # foreman_host.test123 will be created
  + resource "foreman_host" "test123" {
      + __meta__            = (known after apply)
      + bmc_success         = true
      + compute_attributes  = jsonencode(
            {
              + image_id = "/var/lib/libvirt/images/alpine-3.13-cloud.qcow2"
            }
        )
      + compute_profile_id  = 5
      + compute_resource_id = 1
      + domain_id           = 1
      + enable_bmc          = false
      + environment_id      = (known after apply)
      + hostgroup_id        = 3
      + id                  = (known after apply)
      + image_id            = (known after apply)
      + medium_id           = 14
      + method              = "image"
      + model_id            = (known after apply)
      + name                = "test123"
      + operatingsystem_id  = (known after apply)
      + retry_count         = 2

      + interfaces_attributes {
          + id        = (known after apply)
          + ip        = (known after apply)
          + mac       = (known after apply)
          + managed   = true
          + name      = (known after apply)
          + primary   = true
          + provision = false
          + subnet_id = (known after apply)
          + type      = "interface"
          + virtual   = false
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

foreman_host.test123: Creating...
foreman_host.test123: Creation complete after 7s [id=349]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

## second `terraform apply`
If I run `terraform apply` again, you can see that we need to ignore some changes:
```
$ terraform apply
foreman_host.test123: Refreshing state... [id=349]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # foreman_host.test123 has been changed
  ~ resource "foreman_host" "test123" {
      ~ compute_attributes  = jsonencode(
          ~ {
              ~ active             = false -> true
              ~ cputime            = 0 -> 13300000000
              ~ display            = {
                  + port   = "5902"
                    # (2 unchanged elements hidden)
                }
              ~ nics               = [
                  ~ {
                      + bridge  = "virbr1"
                        # (4 unchanged elements hidden)
                    },
                ]
              ~ state              = "shutoff" -> "running"
                # (17 unchanged elements hidden)
            }
        )
        id                  = "349"
        name                = "test123"
      + parameters          = {}
        # (15 unchanged attributes hidden)

      ~ interfaces_attributes {
          + compute_attributes = {}
            id                 = 401
            name               = "test123.virtualt00bz.lan"
            # (8 unchanged attributes hidden)
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

## The problem `terraform destroy`
But then, if I want to destroy the resource. I get an error back from foreman:
```
terraform destroy 
foreman_host.test123: Refreshing state... [id=349]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # foreman_host.test123 has been changed
  ~ resource "foreman_host" "test123" {
      ~ compute_attributes  = jsonencode(
          ~ {
              ~ cputime            = 13300000000 -> 21090000000
                # (21 unchanged elements hidden)
            }
        )
        id                  = "349"
        name                = "test123"
        # (16 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # foreman_host.test123 will be destroyed
  - resource "foreman_host" "test123" {
      - bmc_success         = true -> null
      - compute_attributes  = jsonencode(
            {
              - active             = true
              - arch               = "x86_64"
              - autostart          = false
              - boot_order         = [
                  - "hd",
                ]
              - cpu                = {}
              - cpus               = 1
              - cputime            = 21090000000
              - display            = {
                  - listen = "0.0.0.0"
                  - port   = "5902"
                  - type   = "spice"
                }
              - domain_type        = "kvm"
              - guest_agent        = true
              - hugepages          = false
              - max_memory_size    = 2097152
              - memory             = 2147483648
              - memory_size        = 2097152
              - name               = "test123.virtualt00bz.lan"
              - nics               = [
                  - {
                      - bridge  = "virbr1"
                      - mac     = "52:54:00:18:c9:55"
                      - model   = "virtio"
                      - network = "virtualt00bz.lan"
                      - type    = "network"
                    },
                ]
              - os_type            = "hvm"
              - persistent         = true
              - state              = "running"
              - uuid               = "148edf2b-bac6-4880-b77a-d977d85c8542"
              - virtio_rng         = {}
              - volumes_attributes = {
                  - 0 = {
                      - allocation  = 0
                      - capacity    = 20
                      - format_type = "qcow2"
                      - group       = "0"
                      - id          = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - key         = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - name        = "test123.virtualt00bz.lan-disk1"
                      - owner       = "0"
                      - path        = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - persistent  = true
                      - pool_name   = "default"
                    }
                  - 1 = {
                      - allocation  = 0
                      - capacity    = 0
                      - format_type = "iso"
                      - group       = "0"
                      - id          = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - key         = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - name        = "test123.virtualt00bz.lan-cloud-init.iso"
                      - owner       = "0"
                      - path        = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - persistent  = true
                      - pool_name   = "default"
                    }
                }
            }
        ) -> null
      - compute_profile_id  = 5 -> null
      - compute_resource_id = 1 -> null
      - domain_id           = 1 -> null
      - enable_bmc          = false -> null
      - environment_id      = 1 -> null
      - hostgroup_id        = 3 -> null
      - id                  = "349" -> null
      - image_id            = 8 -> null
      - medium_id           = 14 -> null
      - method              = "image" -> null
      - model_id            = 0 -> null
      - name                = "test123" -> null
      - operatingsystem_id  = 9 -> null
      - owner_id            = 6 -> null
      - owner_type          = "User" -> null
      - parameters          = {} -> null
      - retry_count         = 2 -> null

      - interfaces_attributes {
          - compute_attributes = {} -> null
          - id                 = 401 -> null
          - ip                 = "10.255.200.89" -> null
          - mac                = "52:54:00:18:c9:55" -> null
          - managed            = true -> null
          - name               = "test123.virtualt00bz.lan" -> null
          - primary            = true -> null
          - provision          = true -> null
          - subnet_id          = 1 -> null
          - type               = "interface" -> null
          - virtual            = false -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

foreman_host.test123: Destroying... [id=349]
╷
│ Error: HTTP Error:{
│   endpoint:   [https://foreman.virtualt00bz.lan/api/hosts/349]
│   statusCode: [422]
│   respBody:   [{
│   "error": {"id":349,"errors":{"base":["Selected image does not belong to sleptop7 (Libvirt)"]},"full_messages":["Selected image does not belong to sleptop7 (Libvirt)"]}
│ }
│ ]
│ }
│ 
│ 
╵
```

## The logs from foreman
Then if I go over to the logfile on the foreman server I see:
```
2021-09-01T11:45:08 [I|app|a101914c] Started PUT "/api/hosts/348" for 10.255.0.1 at 2021-09-01 11:45:08 +0000
2021-09-01T11:45:08 [I|app|a101914c] Processing by Api::V2::HostsController#update as JSON
2021-09-01T11:45:08 [I|app|a101914c]   Parameters: {"host"=>{"build"=>false, "comment"=>"", "compute_attributes"=>{"active"=>true, "arch"=>"x86_64", "autostart"=>false, "boot_order"=>["hd"], "cpu"=>{}, "cpus"=>1, "cputime"=>2607590000000, "display"=>{"listen"=>"0.0.0.0", "port"=>"5901", "type"=>"spice"}, "domain_type"=>"kvm", "guest_agent"=>true, "hugepages"=>false, "max_memory_size"=>2097152, "memory"=>2147483648, "memory_size"=>2097152, "name"=>"tftest.virtualt00bz.lan", "nics"=>[{"bridge"=>"virbr1", "mac"=>"52:54:00:c4:95:09", "model"=>"virtio", "network"=>"virtualt00bz.lan", "type"=>"network"}], "os_type"=>"hvm", "persistent"=>true, "state"=>"running", "uuid"=>"3ccfe6f5-3e30-46a9-ba5a-9ccdf0a330f9", "virtio_rng"=>{}, "volumes_attributes"=>{"0"=>{"allocation"=>0, "capacity"=>20, "format_type"=>"qcow2", "group"=>"0", "id"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-disk1", "key"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-disk1", "name"=>"tftest.virtualt00bz.lan-disk1", "owner"=>"0", "path"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-disk1", "persistent"=>true, "pool_name"=>"default"}, "1"=>{"allocation"=>0, "capacity"=>0, "format_type"=>"iso", "group"=>"0", "id"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-cloud-init.iso", "key"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-cloud-init.iso", "name"=>"tftest.virtualt00bz.lan-cloud-init.iso", "owner"=>"0", "path"=>"/var/lib/libvirt/images/tftest.virtualt00bz.lan-cloud-init.iso", "persistent"=>true, "pool_name"=>"default"}}}, "compute_profile_id"=>"5", "compute_resource_id"=>"1", "domain_id"=>"1", "environment_id"=>"1", "hostgroup_id"=>"3", "image_id"=>"8", "interfaces_attributes"=>[{"id"=>400, "subnet_id"=>1, "identifier"=>"", "name"=>"tftest.virtualt00bz.lan", "managed"=>true, "provision"=>true, "virtual"=>false, "primary"=>true, "ip"=>"10.255.200.92", "mac"=>"52:54:00:c4:95:09", "type"=>"interface", "provider"=>"", "_destroy"=>true}], "medium_id"=>"14", "model_id"=>nil, "name"=>"tftest", "operatingsystem_id"=>"9", "owner_id"=>"6", "owner_type"=>"User", "provision_method"=>"image"}, "location_id"=>2, "organization_id"=>1, "apiv"=>"v2", "id"=>"348"}
2021-09-01T11:45:08 [I|app|a101914c] Authorized user terraform(terra form)
2021-09-01T11:45:08 [W|app|a101914c] Selected image does not belong to sleptop7 (Libvirt)
2021-09-01T11:45:08 [W|app|a101914c] Not queueing Host::Managed: ["Selected image does not belong to sleptop7 (Libvirt)"]
2021-09-01T11:45:08 [W|app|a101914c] Not queueing Host::Managed: ["Selected image does not belong to sleptop7 (Libvirt)"]
2021-09-01T11:45:08 [W|app|a101914c] Not queueing Host::Managed: ["Selected image does not belong to sleptop7 (Libvirt)"]
2021-09-01T11:45:08 [E|app|a101914c] Unprocessable entity Host::Managed (id: 348):
  Selected image does not belong to sleptop7 (Libvirt)
```

I see here that there is a `PUT` request on the host and I would have expected a `DELETE` could this maybe be problem? 

## disclaimer
I am a complete n00b when it comes to terraform so the possibility that I am the problem is very real :)

**Comment by lhw** [comment]
I realize the error messages could be presented better.
Could you try referencing the image via the `foreman_image` datasource and in turn as `image_id` in the `foreman_host` resource?

```hcl

data "foreman_image" "alpine" {
  name = "/var/lib/libvirt/images/alpine-3.13-cloud.qcow2"
}

resource "foreman_host" "test123" {
  [...]
  image_id = data.foreman_image.alpine.id
  [...]
}
```

Also generally you don't have to ignore the changes to those fields. Thats mostly just extra information in form of computes attributes.

**Comment by jzandbergen** [comment]
Excellent! Thank you very much. This works a bit better but I am hitting now another error when running `terraform destroy`.

## `main.tf`
```
terraform{
  required_providers {
    foreman = {
      source = "HanseMerkur/foreman"
      version = "0.4.1"
    }
  }
}

provider "foreman" {
  server_hostname = "foreman.virtualt00bz.lan"
  server_protocol = "https"
  client_tls_insecure = true
  client_username = "terraform"
  client_password = "password"
  location_id = 2
  organization_id = 1
  provider_loglevel = "DEBUG"
}


data "foreman_computeresource" "vt00bz" {
  name = "sleptop7"
}

data "foreman_image" "vt00bz" {
  compute_resource_id = 1
  name = "a313"
}

data "foreman_hostgroup" "vt00bz" {
  title = "alpine"
}

data "foreman_computeprofile" "vt00bz" {
  name = "alpine"
}

data "foreman_media" "vt00bz" {
  name = "dummy"
}

resource "foreman_host" "test123" {
  name = "test123"
  hostgroup_id = data.foreman_hostgroup.vt00bz.id
  compute_resource_id = data.foreman_computeresource.vt00bz.id
  compute_profile_id = data.foreman_computeprofile.vt00bz.id
  image_id = data.foreman_image.vt00bz.id
  medium_id = data.foreman_media.vt00bz.id
  method = "image"
  owner_id = 6
  owner_type = "User"
   interfaces_attributes {
     type = "interface"
     managed = true
     primary = true
     provision = true
   }
}
```

Now I can `terraform apply` and `terraform apply` as one would expect. However `terraform destroy` now fails with:

## `terraform destroy`
```
$ terraform destroy
foreman_host.test123: Refreshing state... [id=358]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # foreman_host.test123 will be destroyed
  - resource "foreman_host" "test123" {
      - bmc_success         = true -> null
      - compute_attributes  = jsonencode(
            {
              - active             = false
              - arch               = "x86_64"
              - autostart          = false
              - boot_order         = [
                  - "hd",
                ]
              - cpu                = {}
              - cpus               = 1
              - cputime            = 0
              - display            = {
                  - listen = "0.0.0.0"
                  - type   = "spice"
                }
              - domain_type        = "kvm"
              - guest_agent        = true
              - hugepages          = false
              - max_memory_size    = 2097152
              - memory             = 2147483648
              - memory_size        = 2097152
              - name               = "test123.virtualt00bz.lan"
              - nics               = [
                  - {
                      - mac     = "52:54:00:42:f0:27"
                      - model   = "virtio"
                      - network = "virtualt00bz.lan"
                      - type    = "network"
                    },
                ]
              - os_type            = "hvm"
              - persistent         = true
              - state              = "shutoff"
              - uuid               = "ad93854e-cee1-4645-946a-acc5dd5b0d30"
              - virtio_rng         = {}
              - volumes_attributes = {
                  - 0 = {
                      - allocation  = 0
                      - capacity    = 10
                      - format_type = "qcow2"
                      - group       = "0"
                      - id          = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - key         = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - name        = "test123.virtualt00bz.lan-disk1"
                      - owner       = "0"
                      - path        = "/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1"
                      - persistent  = true
                      - pool_name   = "default"
                    }
                  - 1 = {
                      - allocation  = 0
                      - capacity    = 0
                      - format_type = "iso"
                      - group       = "0"
                      - id          = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - key         = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - name        = "test123.virtualt00bz.lan-cloud-init.iso"
                      - owner       = "0"
                      - path        = "/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso"
                      - persistent  = true
                      - pool_name   = "default"
                    }
                }
            }
        ) -> null
      - compute_profile_id  = 5 -> null
      - compute_resource_id = 1 -> null
      - domain_id           = 1 -> null
      - enable_bmc          = false -> null
      - environment_id      = 1 -> null
      - hostgroup_id        = 3 -> null
      - id                  = "358" -> null
      - image_id            = 10 -> null
      - medium_id           = 14 -> null
      - method              = "image" -> null
      - model_id            = 0 -> null
      - name                = "test123" -> null
      - operatingsystem_id  = 9 -> null
      - owner_id            = 6 -> null
      - owner_type          = "User" -> null
      - parameters          = {} -> null
      - retry_count         = 1 -> null

      - interfaces_attributes {
          - compute_attributes = {} -> null
          - id                 = 410 -> null
          - ip                 = "10.255.200.64" -> null
          - mac                = "52:54:00:42:f0:27" -> null
          - managed            = true -> null
          - name               = "test123.virtualt00bz.lan" -> null
          - primary            = true -> null
          - provision          = true -> null
          - subnet_id          = 1 -> null
          - type               = "interface" -> null
          - virtual            = false -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

foreman_host.test123: Destroying... [id=358]
╷
│ Error: HTTP Error:{
│   endpoint:   [https://foreman.virtualt00bz.lan/api/hosts/358]
│   statusCode: [500]
│   respBody:   [{
│   "error": {"message":"Failed to destroy the record"}
│ }
│ ]
│ }
│ 
│ 
╵

```

On foreman in the logfile we find the following:
```
[...]
2021-09-07T05:29:16 [I|app|cf8ca6ec] Started PUT "/api/hosts/358" for 10.255.0.1 at 2021-09-07 05:29:16 +0000
2021-09-07T05:29:16 [I|app|cf8ca6ec] Processing by Api::V2::HostsController#update as JSON
2021-09-07T05:29:16 [I|app|cf8ca6ec]   Parameters: {"host"=>{"build"=>false, "comment"=>"", "compute_attributes"=>{"active"=>false, "arch"=>"x86_64", "autostart"=>false, "boot_order"=>["hd"], "cpu"=>{}, "cpus"=>1, "cputime"=>0, "display"=>{"listen"=>"0.0.0.0", "type"=>"spice"}, "domain_type"=>"kvm", "guest_agent"=>true, "hugepages"=>false, "max_memory_size"=>2097152, "memory"=>2147483648, "memory_size"=>2097152, "name"=>"test123.virtualt00bz.lan", "nics"=>[{"mac"=>"52:54:00:42:f0:27", "model"=>"virtio", "network"=>"virtualt00bz.lan", "type"=>"network"}], "os_type"=>"hvm", "persistent"=>true, "state"=>"shutoff", "uuid"=>"ad93854e-cee1-4645-946a-acc5dd5b0d30", "virtio_rng"=>{}, "volumes_attributes"=>{"0"=>{"allocation"=>0, "capacity"=>10, "format_type"=>"qcow2", "group"=>"0", "id"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1", "key"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1", "name"=>"test123.virtualt00bz.lan-disk1", "owner"=>"0", "path"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-disk1", "persistent"=>true, "pool_name"=>"default"}, "1"=>{"allocation"=>0, "capacity"=>0, "format_type"=>"iso", "group"=>"0", "id"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso", "key"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso", "name"=>"test123.virtualt00bz.lan-cloud-init.iso", "owner"=>"0", "path"=>"/var/lib/libvirt/images/test123.virtualt00bz.lan-cloud-init.iso", "persistent"=>true, "pool_name"=>"default"}}}, "compute_profile_id"=>"5", "compute_resource_id"=>"1", "domain_id"=>"1", "environment_id"=>"1", "hostgroup_id"=>"3", "image_id"=>"10", "interfaces_attributes"=>[{"id"=>410, "subnet_id"=>1, "identifier"=>"", "name"=>"test123.virtualt00bz.lan", "managed"=>true, "provision"=>true, "virtual"=>false, "primary"=>true, "ip"=>"10.255.200.64", "mac"=>"52:54:00:42:f0:27", "type"=>"interface", "provider"=>"", "_destroy"=>true}], "medium_id"=>"14", "model_id"=>nil, "name"=>"test123", "operatingsystem_id"=>"9", "owner_id"=>"6", "owner_type"=>"User", "provision_method"=>"image"}, "location_id"=>2, "organization_id"=>1, "apiv"=>"v2", "id"=>"358"}
2021-09-07T05:29:16 [I|app|cf8ca6ec] Authorized user terraform(terra form)
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on mac 52:54:00:42:f0:27
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on ip 10.255.200.64
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on type Nic::Managed
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on name test123.virtualt00bz.lan
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on host_id 358
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on subnet_id 1
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on domain_id 1
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on attrs {}
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on provider 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on username 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on password [redacted]
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on virtual false
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on link true
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on identifier 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on tag 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on attached_to 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on managed true
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on mode balance-rr
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on attached_devices 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on bond_options 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on primary true
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on provision true
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on compute_attributes {"type"=>"network", "network"=>"virtualt00bz.lan", "bridge"=>"virtualt00bz.lan", "model"=>"virtio", "from_profile"=>"alpine"}
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on ip6 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on subnet6_id 
2021-09-07T05:29:16 [I|aud|cf8ca6ec] Nic::Managed (410) destroy event on execution true
2021-09-07T05:29:16 [W|app|cf8ca6ec] Rolling back due to exception during save
2021-09-07T05:29:16 [I|app|cf8ca6ec] Backtrace for 'Rolling back due to exception during save' error (ActiveRecord::RecordNotDestroyed): Failed to destroy the record
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/persistence.rb:951:in `_raise_record_not_destroyed'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/persistence.rb:551:in `destroy!'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/associations/has_many_association.rb:99:in `each'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/associations/has_many_association.rb:99:in `delete_records'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/associations/collection_association.rb:385:in `remove_records'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/associations/collection_association.rb:376:in `block in delete_or_destroy'
/opt/theforeman/tfm/root/usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/associations/collection_association.rb:135:in `block in transaction'
[...]
```

I'm not fully sure were to look next, the stacktrace is not very illuminating to me. Also the SQL on the PostgreSQL database is so much that I don't understand what is happening. (Allthough I can see a `ROLLBACK` on that side). So foreman isn't too happy with the request but I am not sure yet why.

**Comment by lhw** [comment]
Your specific bug might be more related to your foreman installation. But I did notice some other bugs with adding/removing nodes at the moment.

**Comment by pja237** [comment]
Hello gentlemen,

also here trying to make the provider to work with a little bit older version of foreman (1.20.1) and failing to delete with exactly the same error/log message.

main.tf resource def:
```
resource "foreman_host" "test" {
  count = var.num_servers

  name = "tf-test-${count.index}"
  hostgroup_id = "14"
  domain_id = "1"
  compute_resource_id = "1"
  interfaces_attributes {
    type = "interface"
    managed   = true
    primary   = true
    provision = true
    subnet_id = "1"

  }

  lifecycle {
    ignore_changes = [
      name,
      compute_attributes,
      interfaces_attributes,
      owner_id,
      image_id,
      owner_type,
      parameters,
    ]
  }
}
```

```
foreman_host.test[8]: Destroying... [id=4592]
foreman_host.test[5]: Destroying... [id=4593]
foreman_host.test[7]: Destroying... [id=4596]
foreman_host.test[6]: Destroying... [id=4595]
foreman_host.test[9]: Destroying... [id=4594]
foreman_host.test[5]: Still destroying... [id=4593, 10s elapsed]
foreman_host.test[9]: Still destroying... [id=4594, 10s elapsed]
╷
│ Error: Put "https://satellite.local.lan/api/hosts/4594": http: ContentLength=2508 with Body length 0
│
│
╵
╷
│ Error: Put "https://satellite.local.lan/api/hosts/4593": http: ContentLength=2508 with Body length 0
│
│
...
```

with foreman production.log saying:

```
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on mac 00:50:56:8d:82:25
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on ip 172.24.19.163
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on type Nic::Managed
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on name tf-test-5.local.lan
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on host_id 4593
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on subnet_id 1
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on domain_id 1
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on attrs {}
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on provider
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on username
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on password [redacted]
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on virtual false
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on link true
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on identifier ens160
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on tag
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on attached_to
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on managed true
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on mode balance-rr
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on attached_devices
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on bond_options
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on primary true
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on provision true
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on compute_attributes {"type"=>"VirtualVmxnet3", "network"=>"Satellite-Servers|tde", "from_profile"=>"TDE Host"}
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on execution true
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on ip6
2021-10-05T13:08:41 [I|aud|170a601f] Nic::Managed (45649) destroy event on subnet6_id
2021-10-05T13:08:41 [W|app|170a601f] Rolling back due to exception during save
ActiveRecord::RecordNotDestroyed: Failed to destroy the record
```

Do you perhaps have any ideas in which directions to try troubleshooting this issue? 

best regards,
Petar

**Comment by lhw** [comment]
Could you please try again with the latest release v0.4.3. I removed some superfluous updates to the host before deletion.

**Comment by pja237** [comment]
@lhw Very sorry for the so late reply, but we have been busy with other projects.
Now we're back at this and i can confirm it works like a charm with version:
```
../terraform version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hansemerkur/foreman v0.4.3
```

```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

foreman_host.test[2]: Destroying... [id=4654]
foreman_host.test[0]: Destroying... [id=4655]
foreman_host.test[1]: Destroying... [id=4653]
foreman_host.test[1]: Still destroying... [id=4653, 10s elapsed]
foreman_host.test[0]: Still destroying... [id=4655, 10s elapsed]
foreman_host.test[2]: Still destroying... [id=4654, 10s elapsed]
foreman_host.test[0]: Destruction complete after 13s
foreman_host.test[1]: Destruction complete after 16s
foreman_host.test[2]: Still destroying... [id=4654, 20s elapsed]
foreman_host.test[2]: Still destroying... [id=4654, 30s elapsed]
foreman_host.test[2]: Still destroying... [id=4654, 40s elapsed]
foreman_host.test[2]: Destruction complete after 44s

Destroy complete! Resources: 3 destroyed.
```

Many thanks for the fix :+1:
